services:
  browsers:
    build: ./playwright-docker
    ports:
      - 3000:3000
    extra_hosts:
      # Access host from container for Mac, Windows and Linux
      # see https://stackoverflow.com/a/43541732
      - "host.docker.internal:host-gateway"
